data_path: "/home/project_cx/G_IR_Diffusion/data/face/data1/fig"
results_dir: "/home/project_cx/G_IR_Diffusion/DiT/results/0404"
model: "DiT-S/8"
image_size: 256
num_classes: 1
epochs: 100
global_batch_size: 256
global_seed: 42
vae: "ema"
num_workers: 4
log_every: 100
ckpt_every: 50000
